### ISSUE TITLE
Bust not showing up

### ISSUE THREAD

**Issue by PiggyPiglet** [surgeplay/Visage#11]
The bust isn't working.

**Comment by exaskye** [comment]
![](https://visage.surgeplay.com/bust/192/e88b3493ea6b42dc94ce1bdfda76ebbd)

The bust is working.

Please explain your issue in more detail.

**Comment by PiggyPiglet** [comment]
Thats strange. I'm clicking render but nothing is happening.
![not working](https://cloud.githubusercontent.com/assets/11957313/21797722/b4feeeac-d74b-11e6-824b-60c3dd82732d.PNG)
This is also for a few others.
Face, Head, Bust and FrontFull aren't working. All the others are.

**Comment by exaskye** [comment]
Confirmed; there's a bad slave running. I've notified its owner and set up a temporary fix.

**Comment by PiggyPiglet** [comment]
Sorry but what do you mean? 'there's a bad slave running.'

**Comment by PiggyPiglet** [comment]
Also it's still not working for me or my server.

**Comment by exaskye** [comment]
Make sure you do a force-reload to get a new image instead of one out of the cache.

Visage is based on a master/slave system. When you make a request to visage.surgeplay.com it's sent to the *master* which then spins off the job to one of many *slaves* connected to it. One of the slaves was broken and returning blank images.

**Comment by PiggyPiglet** [comment]
It's working for my server now. Thanks for fixing it.
