### ISSUE TITLE
Support for webp images

### ISSUE THREAD

**Issue by Puharesource** [surgeplay/Visage#21]
In a recent attempt of optimizing/reducing the amount downloaded resources per request to my website, I started converting all of my website's images to the webp format. Visage images are currently the only images on my website currently not served using webp.

I would write a PR, but I decided not to since I don't know what your stance is on caching two versions of an image .png for legacy browsers / backwards compatibility and the webp format.

Here's a link describing webp in detail: https://developers.google.com/speed/webp/

**Comment by exaskye** [comment]
I'm aware of WebP, but I don't see the advantage with a realtime service like Visage. I'll wind up giving you horribly optimized WebPs in an attempt to not waste server time compressing them, probably resulting in no gains over PNG.

**Comment by Puharesource** [comment]
My concern isn't so much the time it takes to serve the images, but more the amount of bandwidth several images take up on pages that serve a lot of images, such as a users page, where people could be searching through several hundred users before they've found the user they're looking for. For people on 3G or other slow connections having the possibility of a 26% decrease in bandwidth while on such a page is a huge plus.

**Comment by exaskye** [comment]
Yes, but remember I have to not spend all my time compressing images. I can render 9000000000000 avatars no problem, because that's a GPU operation. Compressing an image is CPU, and I can't afford to use all my CPU time compressing WebP images.

So you'd either get WebPs that are worse than PNGs, or I'd use all my server capacity compressing them.

Not to mention the fact basically no browsers support WebP, and calling browsers that don't support it "legacy" is quite a stretch.

I'd sooner implement pngquant (which is fairly fast) or FLIF, than WebP.

**Comment by Puharesource** [comment]
Alright, guess this isn't a possibility then.
