### ISSUE TITLE
Username quota exhausted again

### ISSUE THREAD

**Issue by thomasdaley2** [surgeplay/Visage#37]
After pressing "Render!" you only get a broken/missing image icon.

**FIXED:  You have to use your UUID, Username doesnt seem to be working.**

**Comment by exaskye** [comment]
Mojang gives us a tiny Username→UUID lookup quota, and some people, despite the warnings on the page, are sending mass amounts of username requests.

There's nothing I can do about this until I have more time to work on the project.

**Comment by exaskye** [comment]
I've decided to disable username lookups for good, as they've been down for quite a while now with no real complaints, and they're a pain to try and maintain due to the extremely small quota.

From now on the official service will only allow UUID renders, as has been planned for quite a while.

You can read how to convert usernames to UUIDs yourself at https://wiki.vg/Mojang_API#Username_-.3E_UUID_at_time

For end-user use of the Quick Render panel, you can use a Minecraft UUID lookup service, such as https://mcuuid.net/
