### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by RobertHerhold** [surgeplay/Visage#7]
While doing a request to: https://visage.surgeplay.com/full/512/5d30e92c5ae24284a3ee74bc15077439
Error screenshot: http://oi67.tinypic.com/eq9no1.jpg

**Comment by RobertHerhold** [comment]
Seems to be working now... I'll let @unascribed close this if he wants

**Comment by exaskye** [comment]
Yeah, sorry. I'm dealing with some graphics driver issues.

As you said, it should work now.

**Comment by leMaik** [comment]
@unascribed I just re-started our worker so that Visage doesn't just depend on your graphics card. :+1:

**Comment by exaskye** [comment]
Awesome, thanks! The issues I'm having though are that I'm running the slave on my server now, which has a GPU, but it has outdated graphics drivers. I haven't had the time lately to fix that.

I'm going to set up a software fallback slave today though, so if this happens again and I'm not around to fix it, Visage will just slow down instead of breaking entirely.
